# Generated by Django 5.0.3 on 2024-03-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="airport",
            name="airport_type",
            field=models.CharField(
                choices=[
                    ("civilian", "Civilian"),
                    ("military", "Military"),
                    ("cargo", "Cargo"),
                ],
                default="civilian",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="airport",
            name="city",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="airport",
            name="country",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="airport",
            name="iata_code",
            field=models.CharField(default="", max_length=3),
        ),
        migrations.AddField(
            model_name="airport",
            name="icao_code",
            field=models.CharField(default="", max_length=4),
        ),
    ]
