# Generated by Django 5.0.3 on 2024-03-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_airport_airport_type_airport_city_airport_country_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="airport",
            name="closest_big_city",
        ),
        migrations.AlterField(
            model_name="airport",
            name="city",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="airport",
            name="country",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="airport",
            name="iata_code",
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name="airport",
            name="icao_code",
            field=models.CharField(max_length=4),
        ),
    ]
